# Generated by Django 6.0.1 on 2026-02-03 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5)),
                ('duration', models.PositiveIntegerField(help_text='Time in minutes')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_routes', to='routes.airport')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_routes', to='routes.airport')),
            ],
            options={
                'unique_together': {('parent', 'position')},
            },
        ),
    ]
